# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sajam2019_iod' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sajam2019_iod
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

  target 'sajam2019_iodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sajam2019_iodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
